// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: izpLuD9XfjEg4waoVkj7iA
// Component: ZAbr3NBY_fuT_
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: RIHzkpHfYmQDH/component
import ProductCarousel from "../../ProductCarousel"; // plasmic-import: vNbrVLPgRg9Evc/component
import ProductCard from "../../ProductCard"; // plasmic-import: XuMN_M3Xg6uolp/component
import Ratings from "../../Ratings"; // plasmic-import: AYdZ6jQDwYWu6U/component
import FeatureItem from "../../FeatureItem"; // plasmic-import: p09lbHgG8Ulsh/component
import BlogPost from "../../BlogPost"; // plasmic-import: gtJb5pCoempr4F/component

import { useScreenVariants as useScreenVariants_9LdGg6IuIx6DD } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 9LdGg6iuIX6dD-/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_furn_e_commerce.module.css"; // plasmic-import: izpLuD9XfjEg4waoVkj7iA/projectcss
import sty from "./PlasmicHome.module.css"; // plasmic-import: ZAbr3NBY_fuT_/css

export type PlasmicHome__VariantMembers = {};

export type PlasmicHome__VariantsArgs = {};
type VariantPropType = keyof PlasmicHome__VariantsArgs;
export const PlasmicHome__VariantProps = new Array<VariantPropType>();

export type PlasmicHome__ArgsType = {};
type ArgPropType = keyof PlasmicHome__ArgsType;
export const PlasmicHome__ArgProps = new Array<ArgPropType>();

export type PlasmicHome__OverridesType = {
  root?: p.Flex<"div">;
  header?: p.Flex<typeof Header>;
  productCarousel?: p.Flex<typeof ProductCarousel>;
  productGrid?: p.Flex<"div">;
  featureItem?: p.Flex<typeof FeatureItem>;
};

export interface DefaultHomeProps {}

function PlasmicHome__RenderFunc(props: {
  variants: PlasmicHome__VariantsArgs;
  args: PlasmicHome__ArgsType;
  overrides: PlasmicHome__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_9LdGg6IuIx6DD()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{"My Home Page"}</title>
        <meta key="og:title" property="og:title" content={"My Home Page"} />

        <meta
          key="og:image"
          property="og:image"
          content={
            "https://site-assets.plasmic.app/3c558f23e14c0b925539f28703d24020.png"
          }
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_library_plasmic_color_type_css.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox___5Je2)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__m4J8Y)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__s9QRm)}>
                <Header
                  data-plasmic-name={"header"}
                  data-plasmic-override={overrides.header}
                />

                <ProductCarousel
                  data-plasmic-name={"productCarousel"}
                  data-plasmic-override={overrides.productCarousel}
                  className={classNames("__wab_instance", sty.productCarousel)}
                />
              </div>
            </p.Stack>

            <div className={classNames(projectcss.all, sty.freeBox__z8Qjb)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__v06Fn
                )}
              >
                {"New Arrivals"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              data-plasmic-name={"productGrid"}
              data-plasmic-override={overrides.productGrid}
              hasGap={true}
              className={classNames(projectcss.all, sty.productGrid)}
            >
              <div className={classNames(projectcss.all, sty.column__s8Kvp)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__rXc2U
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__zt1ME)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"160px" as const}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/arrivals1.png",
                        fullWidth: 120,
                        fullHeight: 120,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={true}
                  price={"$65.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__lBtaa
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Wooden Chair"}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__fz39A)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__mi7NW
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__o1IiC)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"160px" as const}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/arrivals2.png",
                        fullWidth: 138,
                        fullHeight: 116,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={true}
                  price={"$80.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__hPhH
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Single Armchair"}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__p1AEn)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__fw4Sl
                  )}
                  image={
                    <p.PlasmicImg
                      alt={"" as const}
                      className={classNames(sty.img__fc3Ui)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"160px" as const}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/arrivals3.png",
                        fullWidth: 135,
                        fullHeight: 116,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$40.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__flMMx
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Wooden Armchair"}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__qxI3)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__sB1Z
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__tiPic)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"160px" as const}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/arrivals4.png",
                        fullWidth: 100,
                        fullHeight: 130,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={true}
                  price={"$100.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__h8VF
                      )}
                      numReviews={"(45 Review)"}
                    />
                  }
                  title={"Stylish Chair"}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__taSfr)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__nepQw
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__n0Wmx)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"160px" as const}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/arrivals5.png",
                        fullWidth: 105,
                        fullHeight: 127,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$120.00"}
                  title={"Modern Chair"}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__wuTa)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__oN0Np
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__w587)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"160px" as const}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/arrivals6.png",
                        fullWidth: 176,
                        fullHeight: 123,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={true}
                  price={"$140.00"}
                  title={"Mapple Wood Dinning Table"}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column___8B8Gg)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__f84Sp
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__m2DeF)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"160px" as const}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/arrivals7.png",
                        fullWidth: 160,
                        fullHeight: 120,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  onSale={true}
                  price={"$90.00"}
                  title={"Arm Chair"}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column___7ZLs3)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__k1RLp
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__wzBkR)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"160px" as const}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/arrivals8.png",
                        fullWidth: 191,
                        fullHeight: 101,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$140.00"}
                  title={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__rIg4I
                      )}
                    >
                      {"Wooden Bed"}
                    </div>
                  }
                />
              </div>
            </p.Stack>

            <FeatureItem
              data-plasmic-name={"featureItem"}
              data-plasmic-override={overrides.featureItem}
              className={classNames("__wab_instance", sty.featureItem)}
            />

            <div className={classNames(projectcss.all, sty.freeBox__v2JeI)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xc6P
                )}
              >
                {"Featured Products"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__eYxJx)}
            >
              <div className={classNames(projectcss.all, sty.column__oNrGr)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__xSrnI
                  )}
                  price={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fo5Ob
                      )}
                    >
                      {"$160.00"}
                    </div>
                  }
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__bvDkA
                      )}
                      numReviews={"(12 Review)"}
                      stars={"two" as const}
                    />
                  }
                  title={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gkCvI
                      )}
                    >
                      {"Designed Sofa"}
                    </div>
                  }
                  withReviews={true}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__iaVm7)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__nnidi
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__hcYlV)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"100%" as const}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/f2.jpeg",
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$200.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__dzStY
                      )}
                      stars={"four" as const}
                    />
                  }
                  title={"Dining Table"}
                  withReviews={true}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__j729F)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__dOo95
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__rWyU)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"100%" as const}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/f3.jpeg",
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$100.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__bxpdl
                      )}
                      numReviews={"(23 Review)"}
                      stars={"five" as const}
                    />
                  }
                  title={"Chair and Table"}
                  withReviews={true}
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__oDycz)}>
                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__zgA5K
                  )}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___4XDsP)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"100%" as const}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/f4.jpeg",
                        fullWidth: 270,
                        fullHeight: 310,
                        aspectRatio: undefined
                      }}
                    />
                  }
                  price={"$299.00"}
                  ratings={
                    <Ratings
                      className={classNames(
                        "__wab_instance",
                        sty.ratings__y9OQs
                      )}
                      numReviews={"(35 Review)"}
                    />
                  }
                  title={"Modern Arm Chair"}
                  withReviews={true}
                />
              </div>
            </p.Stack>

            <div className={classNames(projectcss.all, sty.freeBox__yt9Hx)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qdTom
                )}
              >
                {"Latest Blog"}
              </div>
            </div>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__jR9Re)}
            >
              <div className={classNames(projectcss.all, sty.column___23KlA)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__kRgL4)}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__ttjZl)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"100%" as const}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/b1.jpeg",
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>

              <div className={classNames(projectcss.all, sty.column___5BbX)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__zfqLo)}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__iPzP7)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"100%" as const}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/b2.jpeg",
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>

              <div className={classNames(projectcss.all, sty.column__qb6Qi)}>
                <BlogPost
                  className={classNames("__wab_instance", sty.blogPost__i1Fme)}
                  image={
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__ia2Zq)}
                      displayHeight={"auto" as const}
                      displayMaxHeight={"none" as const}
                      displayMaxWidth={"none" as const}
                      displayMinHeight={"0" as const}
                      displayMinWidth={"0" as const}
                      displayWidth={"100%" as const}
                      src={{
                        src: "/plasmic/furn_e_commerce/images/b3.jpeg",
                        fullWidth: 370,
                        fullHeight: 250,
                        aspectRatio: undefined
                      }}
                    />
                  }
                />
              </div>
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__d4Kw)}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__yheEu)}
                displayHeight={"60px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"none" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"90px" as const}
                src={{
                  src: "/plasmic/furn_e_commerce/images/adidas.png",
                  fullWidth: 90,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img___9Vp)}
                displayHeight={"60px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"none" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"91px" as const}
                src={{
                  src: "/plasmic/furn_e_commerce/images/hm.png",
                  fullWidth: 91,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__s1LLn)}
                displayHeight={"60px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"none" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"98px" as const}
                src={{
                  src: "/plasmic/furn_e_commerce/images/kappa.png",
                  fullWidth: 98,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__u1T5M)}
                displayHeight={"60px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"none" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"124px" as const}
                src={{
                  src: "/plasmic/furn_e_commerce/images/lacoste.png",
                  fullWidth: 124,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />

              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img___2U4AC)}
                displayHeight={"60px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"none" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"125px" as const}
                src={{
                  src: "/plasmic/furn_e_commerce/images/levis.png",
                  fullWidth: 125,
                  fullHeight: 60,
                  aspectRatio: undefined
                }}
              />
            </p.Stack>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header", "productCarousel", "productGrid", "featureItem"],
  header: ["header"],
  productCarousel: ["productCarousel"],
  productGrid: ["productGrid"],
  featureItem: ["featureItem"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: typeof Header;
  productCarousel: typeof ProductCarousel;
  productGrid: "div";
  featureItem: typeof FeatureItem;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHome__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHome__VariantsArgs;
    args?: PlasmicHome__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHome__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHome__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHome__ArgProps,
      internalVariantPropNames: PlasmicHome__VariantProps
    });

    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    productCarousel: makeNodeComponent("productCarousel"),
    productGrid: makeNodeComponent("productGrid"),
    featureItem: makeNodeComponent("featureItem"),

    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
